---
title: "Lydia Messing Around"
author: "Lydia Yoder"
date: "12/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(janitor)
library(tidyverse)
library(dplyr)
```


# Load Data
```{r}
meat <- read_csv("RaguseaMeatWashingSurveyResponsesRaw.csv", 
    col_types = cols(Timestamp = col_datetime(format = "%m/%d/%y %H:%M")), 
    skip = 1) %>% 
  clean_names() %>% 
  filter(age <= 150, age>=9) %>% 
  filter(gender == "Female"|gender=="Male"|gender=="Non-binary"|gender=="Prefer not to disclose")
```

```{r}
meat %>% 
  ggplot(aes(x=age, color = gender))+
  geom_density()

meat %>% 
  group_by(age) %>% 
  summarize(Food_Safety_Importance = mean(food_safety_important)) %>% 
  ggplot(aes(x=age, y=Food_Safety_Importance))+
  geom_point()
  
```

```{r}
recode(meat$country_origin, 
       `United States of America` = "USA",
       `United Kingdom of Great Britain and Northern Ireland` = "UK")

world_map <- map_data("world")

meat_age<- meat %>% 
  mutate(country_origin = recode(meat$country_origin, 
       `United States of America` = "USA",
       `United Kingdom of Great Britain and Northern Ireland` = "UK")) %>% 
  group_by(country_origin) %>% 
  summarize(avg_age = mean(age)) %>% 
  ggplot() +
  geom_map(map = world_map,
           aes(map_id = country_origin,
               fill = avg_age))+
  expand_limits(x = world_map$long, y = world_map$lat) + 
  expand_limits(x = world_map$long, y = world_map$lat)

meat_age

meat_importance<- meat %>% 
  mutate(country_origin = recode(meat$country_origin, 
       `United States of America` = "USA",
       `United Kingdom of Great Britain and Northern Ireland` = "UK")) %>% 
  group_by(country_origin) %>% 
  summarize(avg_importance = mean(food_safety_important)) %>% 
  ggplot() +
  geom_map(map = world_map,
           aes(map_id = country_origin,
               fill = avg_importance))+
  expand_limits(x = world_map$long, y = world_map$lat) + 
  expand_limits(x = world_map$long, y = world_map$lat)

meat_world
meat_importance
```
