---
title: "Sarah's Exploratory Stuff"
author: "Sarah Falkovic"
date: "12/9/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(janitor)
library(tidyverse)
library(gifski)
library(gganimate)
library(patchwork)
```

# Load Data
```{r}
meat <- read_csv("RaguseaMeatWashingSurveyResponsesRaw.csv", 
    col_types = cols(Timestamp = col_datetime(format = "%m/%d/%y %H:%M")), 
    skip = 1) %>% 
  clean_names() %>% 
  rename(reason_health_safety_rank = if_you_do_commonly_wash_any_raw_meat_before_cooking_please_rank_the_following_reasons_with_number_1_being_the_most_relevant_to_you_number_2_next_most_relevant_and_so_on_if_something_isn_t_relevant_leave_the_box_blank_you_may_only_choose_one_row_per_ranking_column_i_m_concerned_about_the_health_and_safety_of_the_meat,
         
         reason_religious_practice_rank = if_you_do_commonly_wash_any_raw_meat_before_cooking_please_rank_the_following_reasons_with_number_1_being_the_most_relevant_to_you_number_2_next_most_relevant_and_so_on_if_something_isn_t_relevant_leave_the_box_blank_you_may_only_choose_one_row_per_ranking_column_i_m_acting_in_accordance_with_a_religious_belief_or_practice,
         
         reason_nonreligious_custom_rank = if_you_do_commonly_wash_any_raw_meat_before_cooking_please_rank_the_following_reasons_with_number_1_being_the_most_relevant_to_you_number_2_next_most_relevant_and_so_on_if_something_isn_t_relevant_leave_the_box_blank_you_may_only_choose_one_row_per_ranking_column_i_m_following_a_non_religious_custom_or_tradition,
         
         reason_appearance_rank = if_you_do_commonly_wash_any_raw_meat_before_cooking_please_rank_the_following_reasons_with_number_1_being_the_most_relevant_to_you_number_2_next_most_relevant_and_so_on_if_something_isn_t_relevant_leave_the_box_blank_you_may_only_choose_one_row_per_ranking_column_i_m_trying_to_improve_the_appearance_of_the_meat,
        
         reason_other_rank = if_you_do_commonly_wash_any_raw_meat_before_cooking_please_rank_the_following_reasons_with_number_1_being_the_most_relevant_to_you_number_2_next_most_relevant_and_so_on_if_something_isn_t_relevant_leave_the_box_blank_you_may_only_choose_one_row_per_ranking_column_other,
         
         reason_improve_texture_rank = if_you_do_commonly_wash_any_raw_meat_before_cooking_please_rank_the_following_reasons_with_number_1_being_the_most_relevant_to_you_number_2_next_most_relevant_and_so_on_if_something_isn_t_relevant_leave_the_box_blank_you_may_only_choose_one_row_per_ranking_column_i_m_trying_to_improve_the_texture_of_the_meat,
         
         reason_improve_taste_rank = if_you_do_commonly_wash_any_raw_meat_before_cooking_please_rank_the_following_reasons_with_number_1_being_the_most_relevant_to_you_number_2_next_most_relevant_and_so_on_if_something_isn_t_relevant_leave_the_box_blank_you_may_only_choose_one_row_per_ranking_column_i_m_trying_to_improve_the_taste_or_smell_of_the_meat,
         
         remove_pathogen_rank = if_you_do_commonly_wash_any_raw_meat_before_cooking_what_are_you_trying_to_remove_rank_the_following_concerns_in_order_of_their_importance_to_you_with_number_1_being_the_most_important_number_2_the_next_most_important_and_so_on_if_something_isn_t_a_concern_to_you_leave_the_box_blank_you_may_only_choose_one_row_per_ranking_column_pathogens_bacteria_viruses_fungi_etc,
         
         remove_inedible_rank = if_you_do_commonly_wash_any_raw_meat_before_cooking_what_are_you_trying_to_remove_rank_the_following_concerns_in_order_of_their_importance_to_you_with_number_1_being_the_most_important_number_2_the_next_most_important_and_so_on_if_something_isn_t_a_concern_to_you_leave_the_box_blank_you_may_only_choose_one_row_per_ranking_column_inedible_debris_dirt_dust_bone_fragments_feathers_etc,
         
         remove_blood_rank = if_you_do_commonly_wash_any_raw_meat_before_cooking_what_are_you_trying_to_remove_rank_the_following_concerns_in_order_of_their_importance_to_you_with_number_1_being_the_most_important_number_2_the_next_most_important_and_so_on_if_something_isn_t_a_concern_to_you_leave_the_box_blank_you_may_only_choose_one_row_per_ranking_column_blood,
         
         remove_liquid_rank = if_you_do_commonly_wash_any_raw_meat_before_cooking_what_are_you_trying_to_remove_rank_the_following_concerns_in_order_of_their_importance_to_you_with_number_1_being_the_most_important_number_2_the_next_most_important_and_so_on_if_something_isn_t_a_concern_to_you_leave_the_box_blank_you_may_only_choose_one_row_per_ranking_column_meat_juice_the_pink_non_blood_liquid_that_comes_out_of_muscle_tissue,
         
         remove_slime_rank = if_you_do_commonly_wash_any_raw_meat_before_cooking_what_are_you_trying_to_remove_rank_the_following_concerns_in_order_of_their_importance_to_you_with_number_1_being_the_most_important_number_2_the_next_most_important_and_so_on_if_something_isn_t_a_concern_to_you_leave_the_box_blank_you_may_only_choose_one_row_per_ranking_column_slime,
         
         remove_chemicals_rank = if_you_do_commonly_wash_any_raw_meat_before_cooking_what_are_you_trying_to_remove_rank_the_following_concerns_in_order_of_their_importance_to_you_with_number_1_being_the_most_important_number_2_the_next_most_important_and_so_on_if_something_isn_t_a_concern_to_you_leave_the_box_blank_you_may_only_choose_one_row_per_ranking_column_artificial_chemicals_preservatives_pesticides_cleaning_solutions_etc,
         
         remove_undesirable_rank = if_you_do_commonly_wash_any_raw_meat_before_cooking_what_are_you_trying_to_remove_rank_the_following_concerns_in_order_of_their_importance_to_you_with_number_1_being_the_most_important_number_2_the_next_most_important_and_so_on_if_something_isn_t_a_concern_to_you_leave_the_box_blank_you_may_only_choose_one_row_per_ranking_column_undesirable_flavors_or_odors,
         
        remove_fat_rank = if_you_do_commonly_wash_any_raw_meat_before_cooking_what_are_you_trying_to_remove_rank_the_following_concerns_in_order_of_their_importance_to_you_with_number_1_being_the_most_important_number_2_the_next_most_important_and_so_on_if_something_isn_t_a_concern_to_you_leave_the_box_blank_you_may_only_choose_one_row_per_ranking_column_fat,
        
        remove_other_rank = if_you_do_commonly_wash_any_raw_meat_before_cooking_what_are_you_trying_to_remove_rank_the_following_concerns_in_order_of_their_importance_to_you_with_number_1_being_the_most_important_number_2_the_next_most_important_and_so_on_if_something_isn_t_a_concern_to_you_leave_the_box_blank_you_may_only_choose_one_row_per_ranking_column_other,
        
        method_water_rinse_bowl_rank = if_you_do_commonly_wash_any_raw_meat_before_cooking_please_rank_the_methods_you_use_with_number_1_being_the_method_you_use_most_often_number_2_next_most_often_and_so_on_if_you_don_t_use_the_method_at_all_leave_the_box_blank_you_may_only_choose_one_row_per_ranking_column_rinsing_in_a_bowl_or_basin_of_plain_water,
        
        method_nonwater_rinse_rank = if_you_do_commonly_wash_any_raw_meat_before_cooking_please_rank_the_methods_you_use_with_number_1_being_the_method_you_use_most_often_number_2_next_most_often_and_so_on_if_you_don_t_use_the_method_at_all_leave_the_box_blank_you_may_only_choose_one_row_per_ranking_column_rinsing_in_anything_other_than_plain_water_salt_brine_vinegar_citrus_etc,
        
        method_running_water_rank = if_you_do_commonly_wash_any_raw_meat_before_cooking_please_rank_the_methods_you_use_with_number_1_being_the_method_you_use_most_often_number_2_next_most_often_and_so_on_if_you_don_t_use_the_method_at_all_leave_the_box_blank_you_may_only_choose_one_row_per_ranking_column_rinsing_under_running_water,
        
        method_nonwater_soak_rank = if_you_do_commonly_wash_any_raw_meat_before_cooking_please_rank_the_methods_you_use_with_number_1_being_the_method_you_use_most_often_number_2_next_most_often_and_so_on_if_you_don_t_use_the_method_at_all_leave_the_box_blank_you_may_only_choose_one_row_per_ranking_column_soaking_awhile_in_anything_other_than_plain_water_salt_brine_vinegar_citrus_etc,
        
        method_other_rank = if_you_do_commonly_wash_any_raw_meat_before_cooking_please_rank_the_methods_you_use_with_number_1_being_the_method_you_use_most_often_number_2_next_most_often_and_so_on_if_you_don_t_use_the_method_at_all_leave_the_box_blank_you_may_only_choose_one_row_per_ranking_column_other,
        
        method_water_soak_rank = if_you_do_commonly_wash_any_raw_meat_before_cooking_please_rank_the_methods_you_use_with_number_1_being_the_method_you_use_most_often_number_2_next_most_often_and_so_on_if_you_don_t_use_the_method_at_all_leave_the_box_blank_you_may_only_choose_one_row_per_ranking_column_soaking_awhile_in_plain_water
  )
```

```{r}
meat <- meat %>% 
  mutate(across(.cols = c(remove_pathogen_rank, remove_chemicals_rank, remove_blood_rank, remove_inedible_rank, remove_undesirable_rank, remove_fat_rank, remove_slime_rank, remove_liquid_rank), .fns = ~fct_relevel(.x, "Of Little Importance", "Unimportant", "Moderately Important", "Important", "Very Important"))) 
```


```{r}
target <- c("Male", "Female", "Non-binary", "Transgender male", "Transgender female", "Prefer not to disclose", "NA")

meat %>% 
  filter(gender == target) %>% 
  ggplot(aes(x = gender, fill = gender))+
  geom_bar() +
  scale_fill_viridis_d(option = "magma") +
  labs(title = "Gender Distribution of Survey Participants",
       x = "  ")

```

```{r}
country_choropleth(plotdata,
                   num_colors=9) +
  scale_fill_brewer(palette="YlOrRd") +
  labs(title = "Life expectancy by country",
       subtitle = "Gapminder 2007 data",
       caption = "source: https://www.gapminder.org",
       fill = "Years")

```

```{r}
library(wesanderson)
library(htmltools)
food.labs <- c("Non-Hispanic", "Hispanic")
names(food.labs) <- c("No", "Yes")


meat %>% 
  filter(houshold_size <= 50,
         hispanic == "Yes"| hispanic == "No") %>% 
  ggplot(aes(x = houshold_size, y = food_safety_important, color = hispanic)) +
  geom_jitter() +
  facet_wrap(vars(hispanic), 
             nrow = 1, 
             labeller = labeller(hispanic = food.labs)) +
  labs( x = "Household Size",
       y = "  ",
       caption = "Ranking on 1 - 5 scale, with 1 being very important and 5 being less important",
       title = "Ranking Food Safety Importance between Household Sizes 
in Hispanic and Non-Hispanic Populations") +
  theme(legend.position = "none") +
  scale_color_manual(values = wes_palette("FantasticFox1"))

```

```{r}
meat %>%
  filter(wash_beef == "Dont Wash"|wash_beef == "Wash"|wash_fowl == "Dont Wash"|wash_fowl == "Wash"|wash_pork== "Dont Wash"|wash_pork == "Wash"|wash_sheep_goat == "Dont Wash"|wash_sheep_goat == "Wash"|wash_ground_meat == "Dont Wash"|wash_ground_meat == "Wash") 
  
```

```{r}
# ranking reasons

aa <- meat %>% 
  summarise(mean(reason_religious_practice_rank, na.rm = TRUE))

a <-meat %>%
  ggplot(aes(x = reason_religious_practice_rank)) +
  geom_histogram(fill = "#ff9b4f") +
  labs(y = "responses", 
       title = "Religious Customs",
       x = "  ") +
  theme(legend.position = "none") +
  geom_vline(aes(xintercept = mean(reason_religious_practice_rank, na.rm = TRUE))) 
# + geom_text(data=data.frame(x=aa, y=0), aes(x + .4, y), label=aa, vjust= -2) 

bb <- meat %>% 
  summarise(mean(reason_religious_practice_rank, na.rm = TRUE))

b <- meat %>%
  ggplot(aes(x = reason_nonreligious_custom_rank)) +
  geom_histogram(fill = "#ff9b4f") +
  labs(y = "responses", 
       title = "Nonreligious Customs",
       x = "  ") +
  theme(legend.position = "none") +
  geom_vline(aes(xintercept = mean(reason_nonreligious_custom_rank, na.rm = TRUE))) 
# + geom_text(data=data.frame(x=bb, y=0), aes(x + .4, y), label=bb, vjust= -2) 

cc <- meat %>% 
  summarise(mean(reason_health_safety_rank, na.rm = TRUE))

c <- meat %>%
  ggplot(aes(x = reason_health_safety_rank)) +
  geom_histogram(fill = "#ff9b4f") +
  labs(y = "responses", 
       title = "Health and Safety",
       x = "  ") +
  theme(legend.position = "none") +
  geom_vline(aes(xintercept = mean(reason_health_safety_rank, na.rm = TRUE))) 
# + geom_text(data=data.frame(x=cc, y=0), aes(x + .4, y), label=cc, vjust= -2) 

dd <- meat %>% 
  summarise(mean(reason_improve_taste_rank, na.rm = TRUE))	

d <- meat %>%
  ggplot(aes(x = reason_improve_taste_rank)) +
  geom_histogram(fill = "#ff9b4f") +
  labs(y = "responses", 
       title = "Improving Taste",
       x = "  ") +
  theme(legend.position = "none") +
  geom_vline(aes(xintercept = mean(reason_improve_taste_rank, na.rm = TRUE))) 
 # + geom_text(data=data.frame(x=dd, y=0), aes(x + .4, y), label=dd, vjust= -2) 


ee <- meat %>% 
  summarise(mean(reason_improve_texture_rank, na.rm = TRUE))	

e <- meat %>%
  ggplot(aes(x = reason_improve_texture_rank)) +
  geom_histogram(fill = "#ff9b4f") +
  labs(y = "responses", 
       title = "Improving Texture",
       x = "  ") +
  theme(legend.position = "none") +
  geom_vline(aes(xintercept = mean(reason_improve_texture_rank, na.rm = TRUE))) 
# + geom_text(data=data.frame(x=ee, y=0), aes(x + .4, y), label=ee, vjust= -2)

ff <- meat %>% 
  summarise(mean(reason_appearance_rank, na.rm = TRUE))	

f <- meat %>%
  ggplot(aes(x = reason_appearance_rank)) +
  geom_histogram(fill = "#ff9b4f") +
  labs(y = "responses", 
       title = "Alter Appearance",
       x = "  ") +
  theme(legend.position = "none") +
  geom_vline(aes(xintercept = mean(reason_appearance_rank, na.rm = TRUE))) 
# + geom_text(data=data.frame(x=ff ,y=0), aes(x + .4, y), label=ff, vjust= -28)

gg <- meat %>%
  summarise(mean(reason_other_rank, na.rm = TRUE))
  
 # 2.390057 mean rank value for "other", found using 

g <- meat %>%
  ggplot(aes(x = reason_other_rank)) +
  geom_histogram(fill = "#ff9b4f") +
  labs(y = "responses", 
       title = "Other Reasons") +
  theme(legend.position = "none") +
  geom_vline(aes(xintercept = mean(reason_other_rank, na.rm = TRUE))) 
# + geom_text(data=data.frame(x = gg ,y=0), aes(x + .4, y), label= 2.390057, vjust= -28)
               

work <-  a + b + c + d + e + f + g + plot_annotation(title = "Why do people choose to wash their meat?", 
                                                     caption = "Ranking on 1 - 7 scale, with 1 being very important and 7 being unimportant, and the line being the average ranking")

work 
```

```{r}
meat %>% 
  summarise(mean(reason_other_rank, na.rm = TRUE),
            )

```

```{r}
#ranking methods

i <-meat %>%
  ggplot(aes(x = method_running_water_rank, fill = "#e3686c")) +
  geom_histogram() +
  labs(y = "responses", 
       title = "Running Water",
       x = "  ") +
  theme(legend.position = "none") +
  geom_vline(aes(xintercept = mean(method_running_water_rank, na.rm = TRUE))) 

j <- meat %>%
  ggplot(aes(x = method_water_rinse_bowl_rank, fill = "#e3686c")) +
  geom_histogram() +
  labs(y = "responses", 
       title = "Water in Bowl",
       x = "  ") +
  theme(legend.position = "none") +
  geom_vline(aes(xintercept = mean(method_water_rinse_bowl_rank, na.rm = TRUE)))

k <- meat %>%
  ggplot(aes(x = method_nonwater_rinse_rank, fill = "#e3686c")) +
  geom_histogram() +
  labs(y = "responses", 
       title = "Nonwater Rinse",
       x = "  ") +
  theme(legend.position = "none") +
  geom_vline(aes(xintercept = mean(method_nonwater_rinse_rank, na.rm = TRUE)))

l <- meat %>%
  ggplot(aes(x = method_water_soak_rank, fill = "#e3686c")) +
  geom_histogram() +
  labs(y = "responses", 
       title = "Soak in Water",
       x = "  ") +
  theme(legend.position = "none") +
  geom_vline(aes(xintercept = mean(method_water_soak_rank, na.rm = TRUE)))

m <- meat %>%
  ggplot(aes(x = method_nonwater_soak_rank, fill = "#e3686c")) +
  geom_histogram() +
  labs(y = "responses", 
       title = "Soak in Nonwater",
       x = "  ") +
  theme(legend.position = "none") +
  geom_vline(aes(xintercept = mean(method_nonwater_soak_rank, na.rm = TRUE)))

n <- meat %>%
  ggplot(aes(x = method_other_rank, fill = "#e3686c")) +
  geom_histogram() +
  labs(y = "responses", 
       title = "Other",
       x = "  ") +
  theme(legend.position = "none") +
  geom_vline(aes(xintercept = mean(method_other_rank, na.rm = TRUE)))
               

methods <-  i + j + k + l + m + n

methods + plot_annotation(title = "Methods for Washing Meat Ranked by Preference", caption = "Nonwater substances are liquids such as acids and salt brines
Ranking on 1 - 5 scale, with 1 being very important and 5 being less important")

```


```{r}
#concerns

o <- meat %>% 
  filter(remove_pathogen_rank != "NA") %>% 
  ggplot(aes(y = remove_pathogen_rank)) +
  geom_bar(fill = "#781380") +
  labs(x = "responses", 
       title = "Pathogens",
       y = "  ") +
  theme(legend.position = "none",
        axis.text = element_text(size = 8)) +
  scale_x_continuous(limits = c(0, 1500),
                     breaks = c(0, 750, 1500))  

p <-meat %>% 
  filter(remove_chemicals_rank != "NA") %>% 
  ggplot(aes(y = remove_chemicals_rank)) +
  geom_bar(fill = "#781380") +
  labs(x = "responses", 
       title = "Chemicals",
       y = "  ") +
  theme(legend.position = "none",
        axis.text = element_text(size = 8))  +
  scale_x_continuous(limits = c(0, 1500),
                     breaks = c(0, 750, 1500))

q <- meat %>% 
  filter(remove_inedible_rank!= "NA") %>% 
  ggplot(aes(y = remove_inedible_rank)) +
  geom_bar(fill = "#781380") +
  labs(x = "responses", 
       title = "Inedible
Portions",
       y = "  ") +
  theme(legend.position = "none",
        axis.text = element_text(size = 8)) +
  scale_x_continuous(limits = c(0, 1500),
                     breaks = c(0, 750, 1500))   

r <- meat %>% 
  filter(remove_undesirable_rank != "NA") %>% 
  ggplot(aes(y = remove_undesirable_rank)) +
  geom_bar(fill = "#781380") +
  labs(x = "responses", 
       title = "Undesirable 
Portions",
       y = "  ") +
  theme(legend.position = "none",
        axis.text = element_text(size = 8)) +
  scale_x_continuous(limits = c(0, 1500),
                     breaks = c(0, 750, 1500)) 
  
s <- meat %>% 
  filter(remove_blood_rank != "NA") %>% 
  ggplot(aes(y = remove_blood_rank)) +
  geom_bar(fill = "#781380") +
  labs(x = "responses", 
       title = "Blood",
       y = "  ") +
  theme(legend.position = "none",
        axis.text = element_text(size = 8)) +
  scale_x_continuous(limits = c(0, 1500),
                     breaks = c(0, 750, 1500)) 

t <- meat %>% 
  filter(remove_slime_rank != "NA") %>% 
  ggplot(aes(y = remove_slime_rank)) +
  geom_bar(fill = "#781380") +
  labs(x = "responses", 
       title = "Slime",
       y = "  ") +
  theme(legend.position = "none",
        axis.text = element_text(size = 8)) +
  scale_x_continuous(limits = c(0, 1500),
                     breaks = c(0, 750, 1500))
  

u <- meat %>% 
  filter(remove_fat_rank != "NA") %>% 
  ggplot(aes(y = remove_fat_rank)) +
  geom_bar(fill = "#781380") +
  labs(x = "responses", 
       title = "Fat",
       y = "  ") +
  theme(legend.position = "none",
        axis.text = element_text(size = 8)) +
  scale_x_continuous(limits = c(0, 1500),
                     breaks = c(0, 750, 1500))   

v <- meat %>% 
  filter(remove_liquid_rank != "NA") %>% 
  ggplot(aes(y = remove_liquid_rank)) +
  geom_bar(fill = "#781380") +
  labs(x = "responses", 
       title = "Liquids",
       y = "  ") +
  theme(legend.position = "none",
        axis.text = element_text(size = 8)) +
  scale_x_continuous(limits = c(0, 1500),
                     breaks = c(0, 750, 1500))   

w <- meat %>% 
  filter(remove_other_rank != "NA") %>% 
  ggplot(aes(y = remove_other_rank)) +
  geom_bar(fill = "#781380") +
  labs(x = "responses", 
       title = "Other",
       y = "  ") +
  theme(legend.position = "none",
        axis.text = element_text(size = 8)) +
  scale_x_continuous(limits = c(0, 50),
                     breaks = c(0, 25, 50))

concerns <-  o + p + q + r + s + t + u + v + w 
concerns + plot_annotation(title = "What is Being Removed when Washing Meat?", caption = "Particpants ranked the most important feature washing removes from the meat.") 
```

```{r}
#removal concern

meat %>% 
  filter(remove_pathogen_rank != "NA") %>% 
  ggplot(aes(x = remove_pathogen_rank)) +
  geom_bar()



```